const mongoose = require("mongoose");

const foodSchema = new mongoose.Schema({
  name: {
    type: String,
  },
  brandOwner: String,
  brandName: String,
  barcode: String,
  userId: String,
  servingQuantity: Number,
  servingQuantityUnit: String,
  servingName: String,
  nutritionalContent: {
    kcal: { type: Number,  default: null },
    totalFat: { type: Number,  default: null },
    saturatedFat: { type: Number,  default: null },
    transFat: { type: Number,  default: null },
    polyunsaturatedFat: { type: Number,  default: null },
    monounsaturatedFat: { type: Number,  default: null },
    cholesterol: { type: Number,  default: null },
    sodium: { type: Number,  default: null },
    totalCarb: { type: Number },
    dietaryFiber: { type: Number,  default: null },
    totalSugar: { type: Number,  default: null },
    addedSugar: { type: Number,  default: null },
    sugarAlcohols: { type: Number,  default: null },
    protein: { type: Number,  default: null },
    vitaminD: { type: Number,  default: null },
    calcium: { type: Number,  default: null },
    iron: { type: Number,  default: null },
    potassium: { type: Number,  default: null },
    vitaminA: { type: Number,  default: null },
    vitaminC: { type: Number,  default: null },
    vitaminE: { type: Number,  default: null },
    thiamin: { type: Number,  default: null },
    riboflavin: { type: Number,  default: null },
    niacin: { type: Number,  default: null },
    vitaminB6: { type: Number,  default: null },
    folate: { type: Number,  default: null },
    vitaminB12: { type: Number,  default: null },
    biotin: { type: Number,  default: null },
    pantothenicAcid: { type: Number,  default: null },
    phosphorus: { type: Number,  default: null },
    iodine: { type: Number,  default: null },
    magnesium: { type: Number,  default: null },
    selenium: { type: Number,  default: null },
  },
  isVerified: Boolean,
});

module.exports = mongoose.model("Food", foodSchema);
