const mongoose = require("mongoose");

const foodSchema = new mongoose.Schema({
  name: {
    type: String,
  },
  brandOwner: String,
  brandName: String,
  barcode: String,
  userId: String,
  servingQuantity: Number,
  servingQuantityUnit: String,
  servingName: String,
  nutritionalContent: {
    kcal: Number,
    totalFat: Number,
    saturatedFat: Number,
    transFat: Number,
    polyunsaturatedFat: Number,
    monounsaturatedFat: Number,
    cholesterol: Number,
    sodium: Number,
    totalCarb: Number,
    dietaryFiber: Number,
    totalSugar: Number,
    addedSugar: Number,
    sugarAlcohols: Number,
    protein: Number,
    vitaminD: Number,
    calcium: Number,
    iron: Number,
    potassium: Number,
    vitaminA: Number,
    vitaminC: Number,
    vitaminE: Number,
    thiamin: Number,
    riboflavin: Number,
    niacin: Number,
    vitaminB6: Number,
    folate: Number,
    vitaminB12: Number,
    biotin: Number,
    pantothenicAcid: Number,
    phosphorus: Number,
    iodine: Number,
    magnesium: Number,
    selenium: Number,
  },
  isVerified: Boolean,
});

module.exports = mongoose.model("Food", foodSchema);
